### ISSUE TITLE
react warning

### ISSUE THREAD

**Issue by janstuemmel** [jniemann66/react-chessdiagram#12]
got following error when rendering Chessdiagram

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by jniemann66** [comment]
Ok - thanks for notifying. Looks like this happens with the new version of React.
Seems a lot of other ppl also having this issue.
I will check it out when i get a chance, but pretty flat-out atm.

[relevant info](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by jniemann66** [comment]
fixed in eefd2aedaeb1ac6351dd36c7b21d1862dc773545
